// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import ()

type Entry struct {
	Domain       string
	Organization string
	Name         string
	Attributes   string
}
